
version: 0.2

phases:
  install:
    commands:
      - echo UPDATING CACHE
      - apt update
  pre_build:
    commands:
      - echo Installing apache...
      - apt install apache2 -y
  build:
    commands:
      - echo starting apache2
      - service apache2 restart
  post_build:
    commands:
      - echo Build completed
